POST http://localhost:8000/sepay/webhook
Authorization: Apikey <example-key>
Content-Type: application/json
Accept: application/json

{
    "id": 92704,
    "gateway": "Techcombank",
    "transactionDate": "2023-03-25 14:02:37",
    "accountNumber": "0123499999",
    "code": null,
    "content": "SDH17156817036",
    "transferType": "in",
    "transferAmount": 2220000,
    "accumulated": 19077000,
    "subAccount": null,
    "referenceCode": "MBVCB.3278907687",
    "description": ""
}
